version: '3.9'

services:
  vitibrasil-api:
    build: .
    container_name: vitibrasil-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
