version: '3.4'

services:
  5mletapivitivinicultura:
    image: 5mletapivitivinicultura
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin123
#    volumes:
#      - mongo-data:/data/db
#    networks:
#      - mongo-net#

#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb  # Nome do serviço do MongoDB
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
#    depends_on:
#      - mongodb  # Espera o MongoDB iniciar
#    networks:
#      - mongo-net#

#networks:
#  mongo-net:
#    driver: bridge#

#volumes:
#  mongo-data:#
